language:  generic

notifications:
    slack: nozeio:LIFY1Jtkx0FRcLq3u1WliHRZ

matrix:
    include:
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-4.2-branch/ubuntu1404/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-07-24-a/swift-4.2-DEVELOPMENT-SNAPSHOT-2018-07-24-a-ubuntu14.04.tar.gz"
          sudo: required
        - os:   Linux
          dist: xenial
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-5.2-release/ubuntu1604/swift-5.2-RELEASE/swift-5.2-RELEASE-ubuntu16.04.tar.gz"
          sudo: required
        - os:   osx
          osx_image: xcode9.4
        - os:   osx
          osx_image: xcode11


before_install:
    - ./.travis.d/before-install.sh

install:
    - ./.travis.d/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - export SWIFTENV_ROOT="$HOME/.swiftenv"
    - export PATH="${SWIFTENV_ROOT}/bin:${SWIFTENV_ROOT}/shims:$PATH"
    - swift build -c release
    - swift build -c debug

